# Generated by Django 5.1.3 on 2024-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('battery_capacity', models.FloatField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ElectricVehicle',
            },
        ),
    ]
