# Generated by Django 5.1.3 on 2024-11-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricvehicle',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='electricvehicle',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='electricvehicle',
            name='registration_date',
        ),
    ]
